name: Commit Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Run GitHub Readme Streak Stats
        uses: Platane/snk@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
